### ISSUE TITLE
logging-improvements

### ISSUE THREAD

**Issue by JimOverholt** [cisco-open/cisco-catalyst-wan-sdk#444]
# Pull Request summary:
Multiple logging improvements

# Description of changes:
1. Fix a bug when response containing unknown encoding caused logging error on Windows host
```
GET /dataservice/stream/device/capture/download/{id}

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 2135: character maps to <undefined>
```
2. Added `elapsed-seconds` in response trace showing response time in seconds
3. Added basic logging for `vManageAuth` requests #146 
4. When custom logger is provided to `create_vManageSession` it also replaces `vManageAuth` instance logger for given session
4. Added `threadName` in default `logger.conf`

Log after changes:
```
2023-03-15 13:24:31 - vmngclient.vmanage_auth - DEBUG - MainThread - <_MainProcess name='MainProcess' parent=None started> app.py:18 <module>(...)
Authenticating: devnetuser POST https://sandbox-sdwan-2.cisco.com/j_security_check <200>
2023-03-15 13:24:32 - vmngclient.vmanage_auth - DEBUG - MainThread - <_MainProcess name='MainProcess' parent=None started> app.py:18 <module>(...)
Authenticating: devnetuser GET https://sandbox-sdwan-2.cisco.com/dataservice/client/token <200>
2023-03-15 13:24:33 - vmngclient.session - DEBUG - MainThread - <_MainProcess name='MainProcess' parent=None started> app.py:18 <module>(...)
{'request': {'method': 'GET',
             'url': 'https://sandbox-sdwan-2.cisco.com/dataservice/client/server',
             'headers': {'User-Agent': 'python-requests/2.28.1',
                         'Accept-Encoding': 'gzip, deflate',
                         'Accept': '*/*',
                         'Connection': 'keep-alive',
                         'Cookie': 'JSESSIONID=qA25_TmQOModN4vArnI9eZBmEiFqwlFOcS223WKG.81ac6722-a226-4411-9d5d-45c0ca7d567b',
                         'x-xsrf-token': 'F28F569D912B40AA0C474245B28A33BFE31D8FF84A8D9A7612A168AA715AB3387D0B78BC7DA321CB7B502B545F681277BEDD'}},
 'response': {'status': 200,
              'reason': 'OK',
              'elapsed-seconds': 0.995,
```

# Checklist:
- [x] Make sure to run pre-commit before commiting changes
- [x] Make sure all checks have passed
- [x] PR description is clear and comprehensive
- [x] Mentioned the issue that this PR solves (if applicable)
- [x] Make sure you test the changes

**Comment by JimOverholt** [comment]
This issue was migrated from an old repository: https://github.com/CiscoDevNet/catalystwan/pull/167
